# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryman',
            options={'ordering': ['p_Name'], 'verbose_name': '配送员', 'verbose_name_plural': '配送员'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'ordering': ['id'], 'verbose_name': '配送单', 'verbose_name_plural': '配送单'},
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='p_Name',
            field=models.CharField(max_length=20, verbose_name='配送员姓名'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='p_Num',
            field=models.IntegerField(verbose_name='配送量'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='p_Phone',
            field=models.CharField(max_length=20, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='p_Sex',
            field=models.IntegerField(choices=[(0, '女'), (1, '男')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='d_Date',
            field=models.DateField(auto_now=True, verbose_name='配送单日期'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='o_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Orders', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='p_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Distribution.Deliveryman', verbose_name='配送员'),
        ),
    ]
