# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_Name', models.CharField(max_length=20)),
                ('g_Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('g_Cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('g_Picture', models.ImageField(upload_to='photos/')),
                ('g_Num', models.IntegerField()),
                ('g_ProductDate', models.DateField()),
                ('g_ExpirationTime', models.IntegerField()),
                ('g_Discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_Name', models.CharField(max_length=20, unique=True)),
                ('t_Description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='t_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods_Type'),
        ),
    ]
