# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['g_Name'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='goods_type',
            options={'ordering': ['t_Name'], 'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_Cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品成本'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_Discount',
            field=models.FloatField(default=1.0, verbose_name='商品折扣'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_ExpirationTime',
            field=models.IntegerField(verbose_name='保质期(月)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_Name',
            field=models.CharField(max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_Num',
            field=models.IntegerField(verbose_name='商品库存'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_Picture',
            field=models.ImageField(upload_to='photos/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_Price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品售价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_ProductDate',
            field=models.DateField(verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='t_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods_Type', verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='goods_type',
            name='t_Description',
            field=models.CharField(blank=True, max_length=100, verbose_name='类别描述'),
        ),
        migrations.AlterField(
            model_name='goods_type',
            name='t_Name',
            field=models.CharField(max_length=20, unique=True, verbose_name='商品类别'),
        ),
    ]
