# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_auto_20160310_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='g_Description',
            field=models.TextField(blank=True, verbose_name='商品描述'),
        ),
    ]
