# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0003_goods_g_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_ExpirationTime',
            field=models.IntegerField(blank=True, verbose_name='保质期(月)'),
        ),
    ]
