# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_auto_20160316_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_Description',
            field=models.TextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_ExpirationTime',
            field=models.IntegerField(verbose_name='保质期(月)'),
        ),
    ]
