# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_Date', models.DateField(auto_now=True)),
                ('o_Status', models.BooleanField()),
                ('o_Amount', models.IntegerField()),
                ('o_Address', models.CharField(max_length=100)),
                ('o_Description', models.CharField(blank=True, max_length=100)),
                ('o_Contact', models.CharField(max_length=20)),
                ('o_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('c_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
                ('g_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods')),
            ],
        ),
    ]
