# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['id'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='c_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='g_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_Address',
            field=models.CharField(max_length=100, verbose_name='配送地址'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_Amount',
            field=models.IntegerField(verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_Contact',
            field=models.CharField(max_length=20, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_Date',
            field=models.DateField(auto_now=True, verbose_name='订单日期'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_Description',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_Status',
            field=models.BooleanField(verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='o_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单总额'),
        ),
    ]
