# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Name', models.CharField(max_length=20)),
                ('c_Phone', models.CharField(max_length=20, unique=True)),
                ('c_Address', models.CharField(max_length=100)),
                ('c_Cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('c_Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_Description', models.CharField(blank=True, max_length=100)),
                ('m_Discount', models.FloatField()),
                ('m_Level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='m_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Member'),
        ),
    ]
