# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_customer_m_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='m_Level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Customer.Member', verbose_name='会员等级'),
        ),
    ]
