# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-c_Date'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_Content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_Date',
            field=models.DateField(verbose_name='评论日期'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='g_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods', verbose_name='商品'),
        ),
    ]
